[pytest]
# Минимальная версия Python
minversion = 3.11

# Опции по умолчанию при запуске
addopts = 
    --alluredir=allure-results
    -v
    --tb=short

# Маркеры для тестов
markers =
    smoke: Smoke тесты
    regression: Regression тесты
    positive: Позитивные сценарии
    negative: Негативные сценарии

# Директория с тестами
testpaths = tests

# Паттерн для поиска тестов
python_files = test_*.py
python_classes = Test*
python_functions = test_*
